version: '3.9'

services:
  db:
    image: postgres

    environment:
      POSTGRES_USER: "black"
      POSTGRES_PASSWORD: "black"
      POSTGRES_DB: "black"
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: localhost
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    ports:
      - 15672:15672
      - 5672:5672