version: '3.9'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: transaction
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
